<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="3">

  <testsuite name="tests"
    errors="1" failures="0" hostname="" id="" package="tests" skipped="2"
    tests="3" time="0.005000" timestamp="Mon, 22 Jan 2018 23:20:10 GMT">
  
    <testcase name="UICheck" classname="tests" time="0.005000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Tests / UICheck]:

  TypeError: functions.UIChecker is not a function
    at Object.UICheck (C:\devmtn\nightwatch-introduction-part1\nightwatch\step3\tests\tests.js:14:37)
    at Module.call (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
    
    <testcase
      name="2+2=4" classname="tests">
      <skipped />
    </testcase>
    
    <testcase
      name="32.1*2=64.2" classname="tests">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
